# Generated by Django 3.2.3 on 2021-06-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EMPLOYEE_ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('EMAIL_ID', models.EmailField(max_length=100)),
                ('AGE', models.CharField(max_length=100)),
                ('OCCUPATION', models.CharField(max_length=100)),
            ],
        ),
    ]
